pipeline {
    agent any
    tools {
        go 'go'
    }

    environment{
        GO111MODULE='on'
    }

    stages{
        stage('Develpment'){
            steps{
                git 'https://github.com/AdminTurnedDevops/go-webapp-sample.git'
            }
        }
        stage('Image'){
            steps{
                script {
                    app= docker.build("AdminTurnedDevops/go-webapp-sample")
                }
            }
        }
    }
}